# Generated by Django 5.0.6 on 2024-06-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('Aadhaar', models.CharField(max_length=12)),
                ('Pincode', models.CharField(max_length=6)),
                ('CustId', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
    ]
